/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INoteNFT,
  INoteNFTInterface,
} from "../../../contracts/RewardVault.sol/INoteNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "authorOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INoteNFT__factory {
  static readonly abi = _abi;
  static createInterface(): INoteNFTInterface {
    return new Interface(_abi) as INoteNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INoteNFT {
    return new Contract(address, _abi, runner) as unknown as INoteNFT;
  }
}
